/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelRouteImport } from './routes/_panel'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PanelAdministracionRouteImport } from './routes/_panel.administracion'
import { Route as PanelCalendarioRouteImport } from './routes/_panel.calendario'
import { Route as PanelConfiguracionRouteImport } from './routes/_panel.configuracion'
import { Route as PanelConsultasRouteImport } from './routes/_panel.consultas'
import { Route as PanelDashboardRouteImport } from './routes/_panel.dashboard'
import { Route as PanelLeadsRouteImport } from './routes/_panel.leads'
import { Route as PanelPacientesRouteImport } from './routes/_panel.pacientes'
import { Route as PanelProfesionalesRouteImport } from './routes/_panel.profesionales'
import { Route as PanelTratamientosRouteImport } from './routes/_panel.tratamientos'
import { Route as PanelWhatsappRouteImport } from './routes/_panel.whatsapp'
import { Route as PanelPacientesIdRouteImport } from './routes/_panel.pacientes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAdministracionRoute = PanelAdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCalendarioRoute = PanelCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => PanelRoute,
} as any)
const PanelConfiguracionRoute = PanelConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => PanelRoute,
} as any)
const PanelConsultasRoute = PanelConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => PanelRoute,
} as any)
const PanelDashboardRoute = PanelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PanelRoute,
} as any)
const PanelLeadsRoute = PanelLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPacientesRoute = PanelPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => PanelRoute,
} as any)
const PanelProfesionalesRoute = PanelProfesionalesRouteImport.update({
  id: '/profesionales',
  path: '/profesionales',
  getParentRoute: () => PanelRoute,
} as any)
const PanelTratamientosRoute = PanelTratamientosRouteImport.update({
  id: '/tratamientos',
  path: '/tratamientos',
  getParentRoute: () => PanelRoute,
} as any)
const PanelWhatsappRoute = PanelWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPacientesIdRoute = PanelPacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PanelPacientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/administracion': typeof PanelAdministracionRoute
  '/calendario': typeof PanelCalendarioRoute
  '/configuracion': typeof PanelConfiguracionRoute
  '/consultas': typeof PanelConsultasRoute
  '/dashboard': typeof PanelDashboardRoute
  '/leads': typeof PanelLeadsRoute
  '/pacientes': typeof PanelPacientesRouteWithChildren
  '/profesionales': typeof PanelProfesionalesRoute
  '/tratamientos': typeof PanelTratamientosRoute
  '/whatsapp': typeof PanelWhatsappRoute
  '/pacientes/$id': typeof PanelPacientesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/administracion': typeof PanelAdministracionRoute
  '/calendario': typeof PanelCalendarioRoute
  '/configuracion': typeof PanelConfiguracionRoute
  '/consultas': typeof PanelConsultasRoute
  '/dashboard': typeof PanelDashboardRoute
  '/leads': typeof PanelLeadsRoute
  '/pacientes': typeof PanelPacientesRouteWithChildren
  '/profesionales': typeof PanelProfesionalesRoute
  '/tratamientos': typeof PanelTratamientosRoute
  '/whatsapp': typeof PanelWhatsappRoute
  '/pacientes/$id': typeof PanelPacientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_panel': typeof PanelRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/_panel/administracion': typeof PanelAdministracionRoute
  '/_panel/calendario': typeof PanelCalendarioRoute
  '/_panel/configuracion': typeof PanelConfiguracionRoute
  '/_panel/consultas': typeof PanelConsultasRoute
  '/_panel/dashboard': typeof PanelDashboardRoute
  '/_panel/leads': typeof PanelLeadsRoute
  '/_panel/pacientes': typeof PanelPacientesRouteWithChildren
  '/_panel/profesionales': typeof PanelProfesionalesRoute
  '/_panel/tratamientos': typeof PanelTratamientosRoute
  '/_panel/whatsapp': typeof PanelWhatsappRoute
  '/_panel/pacientes/$id': typeof PanelPacientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/login'
    | '/nosotros'
    | '/servicios'
    | '/administracion'
    | '/calendario'
    | '/configuracion'
    | '/consultas'
    | '/dashboard'
    | '/leads'
    | '/pacientes'
    | '/profesionales'
    | '/tratamientos'
    | '/whatsapp'
    | '/pacientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/login'
    | '/nosotros'
    | '/servicios'
    | '/administracion'
    | '/calendario'
    | '/configuracion'
    | '/consultas'
    | '/dashboard'
    | '/leads'
    | '/pacientes'
    | '/profesionales'
    | '/tratamientos'
    | '/whatsapp'
    | '/pacientes/$id'
  id:
    | '__root__'
    | '/'
    | '/_panel'
    | '/contacto'
    | '/login'
    | '/nosotros'
    | '/servicios'
    | '/_panel/administracion'
    | '/_panel/calendario'
    | '/_panel/configuracion'
    | '/_panel/consultas'
    | '/_panel/dashboard'
    | '/_panel/leads'
    | '/_panel/pacientes'
    | '/_panel/profesionales'
    | '/_panel/tratamientos'
    | '/_panel/whatsapp'
    | '/_panel/pacientes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRoute: typeof PanelRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  LoginRoute: typeof LoginRoute
  NosotrosRoute: typeof NosotrosRoute
  ServiciosRoute: typeof ServiciosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/administracion': {
      id: '/_panel/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof PanelAdministracionRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/calendario': {
      id: '/_panel/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof PanelCalendarioRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/configuracion': {
      id: '/_panel/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof PanelConfiguracionRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/consultas': {
      id: '/_panel/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof PanelConsultasRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/dashboard': {
      id: '/_panel/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PanelDashboardRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/leads': {
      id: '/_panel/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof PanelLeadsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/pacientes': {
      id: '/_panel/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PanelPacientesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/profesionales': {
      id: '/_panel/profesionales'
      path: '/profesionales'
      fullPath: '/profesionales'
      preLoaderRoute: typeof PanelProfesionalesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/tratamientos': {
      id: '/_panel/tratamientos'
      path: '/tratamientos'
      fullPath: '/tratamientos'
      preLoaderRoute: typeof PanelTratamientosRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/whatsapp': {
      id: '/_panel/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof PanelWhatsappRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/pacientes/$id': {
      id: '/_panel/pacientes/$id'
      path: '/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof PanelPacientesIdRouteImport
      parentRoute: typeof PanelPacientesRoute
    }
  }
}

interface PanelPacientesRouteChildren {
  PanelPacientesIdRoute: typeof PanelPacientesIdRoute
}

const PanelPacientesRouteChildren: PanelPacientesRouteChildren = {
  PanelPacientesIdRoute: PanelPacientesIdRoute,
}

const PanelPacientesRouteWithChildren = PanelPacientesRoute._addFileChildren(
  PanelPacientesRouteChildren,
)

interface PanelRouteChildren {
  PanelAdministracionRoute: typeof PanelAdministracionRoute
  PanelCalendarioRoute: typeof PanelCalendarioRoute
  PanelConfiguracionRoute: typeof PanelConfiguracionRoute
  PanelConsultasRoute: typeof PanelConsultasRoute
  PanelDashboardRoute: typeof PanelDashboardRoute
  PanelLeadsRoute: typeof PanelLeadsRoute
  PanelPacientesRoute: typeof PanelPacientesRouteWithChildren
  PanelProfesionalesRoute: typeof PanelProfesionalesRoute
  PanelTratamientosRoute: typeof PanelTratamientosRoute
  PanelWhatsappRoute: typeof PanelWhatsappRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelAdministracionRoute: PanelAdministracionRoute,
  PanelCalendarioRoute: PanelCalendarioRoute,
  PanelConfiguracionRoute: PanelConfiguracionRoute,
  PanelConsultasRoute: PanelConsultasRoute,
  PanelDashboardRoute: PanelDashboardRoute,
  PanelLeadsRoute: PanelLeadsRoute,
  PanelPacientesRoute: PanelPacientesRouteWithChildren,
  PanelProfesionalesRoute: PanelProfesionalesRoute,
  PanelTratamientosRoute: PanelTratamientosRoute,
  PanelWhatsappRoute: PanelWhatsappRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRoute: PanelRouteWithChildren,
  ContactoRoute: ContactoRoute,
  LoginRoute: LoginRoute,
  NosotrosRoute: NosotrosRoute,
  ServiciosRoute: ServiciosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
